version: '3.8'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
    volumes:
      - .:/code
    ports:
    - 8000:8000
    depends_on:
      - db
    
  db:
    restart: always
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=Hello_Docker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Amishobjani25
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: Amishobjani25
    ports:
      - "5050:80"
    volumes:
      - my-data:/var/lib/pgadmin
    

volumes:
  postgres_data:
  my-data: